//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utiles.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(DESCRIPTION =    (ADDRESS_LIST =      (ADDRESS = (PROTOCOL = TCP)(HO" +
            "ST = 192.168.1.58)(PORT = 1521))    )    (CONNECT_DATA = (SID = dbgrinya))  );Us" +
            "er Id=grinya_expert;Password=datadec;")]
        public string Conex_Expert {
            get {
                return ((string)(this["Conex_Expert"]));
            }
            set {
                this["Conex_Expert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.195\\sqlserver2008;Initial Catalog=QC600;Persist Security In" +
            "fo=True;User ID=dso;Password=dsodsodsData Source=192.168.1.195\\sqlserver2008;Ini" +
            "tial Catalog=QC600;Persist Security Info=True;User ID=dso;Password=dsodsodso")]
        public string Conex_Quality {
            get {
                return ((string)(this["Conex_Quality"]));
            }
            set {
                this["Conex_Quality"] = value;
            }
        }
    }
}
